# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 915dd2681b7a2c6fbf7bc441e0e247cec1d7b7e8c077bcb447166d7d8531f6edf64fcc8da029f245c559e7771af4e90cc1addf4bdb644c296bc29c2dc87ca977

test:
  secret_key_base: cbce861cc3115a13d26c83b06858af509dfb2caabb124d7687dc4a274d2851310a18dcb0bd2a9d9c5347778434588b3b52fb999eab00bc9cef8a0a4ef82c90fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
